# Generated by Django 5.0.3 on 2024-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_animal_prize_animal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/150', upload_to='animal_images'),
        ),
    ]
