# Generated by Django 5.0.3 on 2024-03-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_animal_animal_prize_alter_animal_animal_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Animal_color',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
