# Generated by Django 5.0.3 on 2024-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_animal_animal_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Animal_Prize',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Animal_Weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
