# Generated by Django 5.0.4 on 2024-04-26 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_animal_description_animal_animal_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Animal_color',
            new_name='animal_color',
        ),
    ]
