# Generated by Django 5.0.4 on 2024-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_animal_farm_animal_animal_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
